travis:
  secure:
    BINSTAR_TOKEN: sGMNB48k0LFVAg2UKGRcEUCwv1FcBwGaSFBIHSQsdKYgrz2u/opP1uWgIR82qpjbpP1uoOJyqJ8VhhuyU1PGeVWQnEuB7MA258zv8WHy74hw7vZVw8hhzM6VxFD07i2ndHXtfPnsp7X9W3/6Xd01TOb3zvVyLnGy22sDUqCHArMD4j/IjTUp7O22uzqvbbUgm5elETpeZNRhmkN6aO2mop3ZGuG3B+tbyqQqblyenEabA9umkAREXHb3o4QayrgezRpo1sX1L6X0W49l4aGcXRFJ5XqSgKOBX132Xc3yTjSzEGO0KR1QmrbB1P+4ub69oPgoojdafdROjpBeE5hw58PNFNV6204Nr+fs+0Imvk6tS/2dKbaVtlTctG2vwh0oSiGDGKI2P7D/mB7yxvRak7fJismIIp3nxfnlZ7r6vZtJmYYssBGsilINlBebfvtlNQnDlM/za8Tln/BGxz1RmvUrsNiDPLiouEr71LEbxyTtu83S3R7kvRJ2giw4vhKXoE96Wg6raccMIOlsk5Q0DsVIY6sbBrt1GdnhDcZnpNOobmPGTlb/MGfys1l3e7jjvbf55zUXPlOWlXYjPcE8dAyugSyQpqAlRsz61AwwLotfDKZ2wjihPgbdZGmJ24lgFbBm7lwDDKdUpRdofA5gAXa5EF9veZ8qirAfjz+j/jk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
